[workspace]
members = [
    "aggregator",
    "alerting",
    "aster",
    "billable",
    "billing",
    "collector",
    "common",
    "connector",
    "controller",
    "dashboard",
    "notification",
]
