[workspace]
members = [
    "aggregator",
    "alerting",
    "aster",
    "billable",
    "billing",
    "collector",
    "common",
    "connector",
    "controller",
    "dashboard",
    "notification",
    "frontend_server"
]
default-members = ["aster"]
