[package]
name = "alerting"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
common = { path = "../common" }
async-trait = "0.1.68"
notification = { path = "../notification" }
anyhow = "1.0.71"
log = "0.4.18"