name: Release Drafter

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5.23.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
