[package]
name = "billable"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
chrono = "0.4.26"
async-trait = "0.1.51"
log = "0.4.18"
anyhow = "1.0.71"